# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestingDataverseConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivedescription', models.TextField(blank=True, null=True)),
                ('archiveurl', models.CharField(blank=True, max_length=255, null=True)),
                ('harveststyle', models.CharField(blank=True, max_length=255, null=True)),
                ('harvesttype', models.CharField(blank=True, max_length=255, null=True)),
                ('harvestingset', models.CharField(blank=True, max_length=255, null=True)),
                ('harvestingurl', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'harvestingdataverseconfig',
                'managed': False,
            },
        ),
    ]
