# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-03 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvesting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestingClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivedescription', models.TextField(blank=True, null=True)),
                ('archiveurl', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.NullBooleanField()),
                ('harveststyle', models.CharField(blank=True, max_length=255, null=True)),
                ('harvesttype', models.CharField(blank=True, max_length=255, null=True)),
                ('harvestingnow', models.NullBooleanField()),
                ('harvestingset', models.CharField(blank=True, max_length=255, null=True)),
                ('harvestingurl', models.CharField(blank=True, max_length=255, null=True)),
                ('metadataprefix', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('scheduledayofweek', models.IntegerField(blank=True, null=True)),
                ('schedulehourofday', models.IntegerField(blank=True, null=True)),
                ('scheduleperiod', models.CharField(blank=True, max_length=255, null=True)),
                ('scheduled', models.NullBooleanField()),
            ],
            options={
                'db_table': 'harvestingclient',
                'managed': False,
            },
        ),
    ]
