# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datafiles', '0005_filemetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatafileCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'datafilecategory',
                'managed': False,
                'verbose_name_plural': 'Datafile categories',
            },
        ),
        migrations.CreateModel(
            name='DatafileTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtype', models.IntegerField(db_column=b'type')),
            ],
            options={
                'db_table': 'datafiletag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FilemetadataDatafileCategory',
            fields=[
                ('filemetadatas', models.ForeignKey(db_column=b'filemetadatas_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='datafiles.FileMetadata')),
            ],
            options={
                'db_table': 'filemetadata_datafilecategory',
                'verbose_name': 'File metadata datafile category',
                'verbose_name_plural': 'File metadata datafile categories',
                'managed': False,
            },
        ),
    ]
