swagger: "2.0"

info:
version: 0.5.0
title: Dataverser Metrics API
description: An API for Dataverse metrics. (internal use)

schemes:
- http
host: 127.0.0.1:8000
basePath: /metrics/v1

paths:
/datasets/count/monthly:
get:
  summary: Number of new Datasets added each month
  description: Returns a list of counts and cumulative counts of all datasts added in a month
  parameters:
    - $ref: "#/parameters/startDateParam"
    - $ref: "#/parameters/endDateParam"
    - $ref: "#/parameters/selectedYearParam"
    - $ref: "#/parameters/prettyJSONParam"
  responses:
    200:
      description: A list of Dataset counts by month
      schema:
        $ref: "#/definitions/MonthCounts"
    400:
      description: Parameter error

# ------------------------------
# Define reusable parameters:
# ------------------------------
parameters:
  startDateParam:
    name: start_date
    in: query
    description: Optional. Inclusive start date in YYYY-MM-DD format
    type: string
  endDateParam:
    name: end_date
    in: query
    description: Optional. Inclusive end date in YYYY-MM-DD format
    type: string
  selectedYearParam:
    name: selected_year
    in: query
    description: Optional. Selected year in YYYY format
    type: string
  timeSortParam:
    name: time_sort
    in: query
    description: Optional. Sort by time.  'a' = ascending; 'd' = descending
    type: string
  prettyJSONParam:
    name: pretty
    in: query
    description: Optional. Returns HTML response showing formatted JSON
    type: boolean

# ------------------------------
# Define response definitions
# ------------------------------
definitions:
  MonthCount:
    properties:
      cnt:
        type: integer
      running_total:
        type: integer
      yyyy_mm:
        type: string
      month_name:
        type: string
      year_num:
        type: integer
      month_num:
        type: integer
  MonthCounts:
    type: array
    items:
      $ref: "#/definitions/MonthCount"
