# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-13 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0004_auto_20160906_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
