# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-20 14:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0005_auto_20160913_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='full_name',
            field=models.CharField(default=datetime.datetime(2016, 9, 20, 14, 27, 28, 844454, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installation',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
