# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-23 00:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0007_auto_20160920_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Needs be active to show on dataverse.org map'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='version',
            field=models.CharField(blank=True, default=datetime.datetime(2016, 9, 23, 0, 29, 31, 272739, tzinfo=utc), help_text='Dataversion version.  e.g. "4.3", "3.6.2", etc', max_length=6),
            preserve_default=False,
        ),
    ]
