# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datafiles', '0002_auto_20160628_2043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datafile',
            options={'managed': False, 'ordering': ('id',)},
        ),
    ]
