# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataverses', '0005_auto_20160628_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citationpagecheck',
            name='dataverse',
        ),
        migrations.DeleteModel(
            name='CitationPageCheck',
        ),
    ]
