# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataverses', '0006_auto_20160802_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataverseContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactemail', models.CharField(max_length=255)),
                ('displayorder', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('displayorder', 'contactemail'),
                'db_table': 'dataversecontact',
                'managed': False,
            },
        ),
    ]
