# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-05 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataverses', '0007_dataversecontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataverseLinkingDataverse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkcreatetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dataverselinkingdataverse',
                'managed': False,
            },
        ),
    ]
