# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField()),
                ('emailrequired', models.NullBooleanField()),
                ('enabled', models.NullBooleanField()),
                ('institutionrequired', models.NullBooleanField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('namerequired', models.NullBooleanField()),
                ('positionrequired', models.NullBooleanField()),
            ],
            options={
                'db_table': 'guestbook',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GuestBookResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloadtype', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('institution', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('responsetime', models.DateTimeField(blank=True, null=True)),
                ('sessionid', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'guestbookresponse',
                'managed': False,
            },
        ),
    ]
