swagger: "2.0"

info:
  title: Dataverse Metrics API
  description: An API for Dataverse metrics. (internal use)
  version: 0.5.0

# the domain of the service
host: {{ SWAGGER_HOST }}
# array of all schemes that your API supports
schemes:
  - {{ SWAGGER_SCHEME }}
# will be prefixed to all paths
basePath: /metrics/v1
produces:
  - application/json

{% for endpoint in endpoints %}
{% if forloop.first %}paths:{% endif %}
{{ endpoint }}
{% endfor %}

# ------------------------------
# Define reusable parameters:
# ------------------------------
parameters:
  startDateParam:
    name: start_date
    in: query
    description: Optional. Inclusive start date in YYYY-MM-DD format
    type: string
  endDateParam:
    name: end_date
    in: query
    description: Optional. Inclusive end date in YYYY-MM-DD format
    type: string
  selectedYearParam:
    name: selected_year
    in: query
    description: Optional. Selected year in YYYY format
    type: string
  timeSortParam:
    name: time_sort
    in: query
    description: Optional. Sort by time.  'a' = ascending; 'd' = descending
    type: string
  publicationStateParam:
    name: pub_state
    in: query
    description: Optional. Specify whether to include published records, unpublished records, or all. Defaults to "published"
    type: string
    enum:
      - published
      - unpublished
      - all
  prettyJSONParam:
    name: pretty
    in: query
    description: Optional. Returns HTML response showing formatted JSON
    type: boolean
  showUncategorizedParam:
    name: show_uncategorized
    in: query
    description: Optional. For Dataverse type counts, show uncategorized Dataverses.
    type: boolean
  contentTypeParam:
    name: ctype
    in: query
    description: Optional. Value from the Filemetadata 'contenttype' column. e.g. "application/octet-stream", "data/various-formats", etc
    type: string
  dataverseAPIKey:
    name: key
    in: query
    description: Dataverse API key.  Required for production use.  See http://guides.dataverse.org/en/latest/api/native-api.html
    type: string

# ------------------------------
# Define response definitions
# ------------------------------
definitions:
  MonthCount:
    properties:
      cnt:
        type: integer
      running_total:
        type: integer
      yyyy_mm:
        type: string
      month_name:
        type: string
      year_num:
        type: integer
      month_num:
        type: integer
  MonthCounts:
    type: array
    items:
      $ref: "#/definitions/MonthCount"
  FileExtensionCount:
    properties:
      extension:
        type: string
      count:
        type: integer
  FileExtensionCounts:
    type: array
    items:
      $ref: "#/definitions/FileExtensionCount"
  NumberUniqueExtensions:
    properties:
      number_unique_extensions:
        type: integer
  AffiliationCount:
    properties:
      affiliation:
        type: string
      affil_count:
        type: integer
      total_count:
        type: integer
      percent_string:
        type: string
  AffiliationCounts:
    type: array
    items:
      $ref: "#/definitions/AffiliationCount"
  DataverseTypeCount:
    properties:
      dataversetype:
        type: string
      dataversetype_label:
        type: string
      type_count:
        type: integer
      total_count:
        type: integer
      percent_string:
        type: string
  DataverseTypeCounts:
    type: array
    items:
      $ref: "#/definitions/DataverseTypeCount"
  FileTypeCount:
    properties:
      contenttype:
        type: string
      short_content_type:
        type: string
      type_count:
        type: integer
      total_count:
        type: integer
      percent_string:
        type: string
  FileTypeCounts:
    type: array
    items:
      $ref: "#/definitions/FileTypeCount"
  DatasetSubjectCount:
    properties:
      subject:
        type: string
      count:
        type: integer
      percent_string:
        type: string
      percent_number:
        type: number
      total_count:
        type: integer
  DatasetSubjectCounts:
    type: array
    items:
      $ref: "#/definitions/DatasetSubjectCount"
